# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89001fe5138091c37c8a95538c5abdcf1ea527720d207ca909811b9b73cf7473621aea338a971aabca70dc0080439b78b5751b61483c8acf48242a2487f26275

test:
  secret_key_base: 0c7267c5a0cb111e03f4f96ae0bb03d6c2a6d762cb12465910f69bd0cf28ed11b34094de7d333ac075feaa7deabf9f4bc85b86882362fbf511f70019a6ed33dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
